sudo: required

language: c++

os:
  - linux

arch:
  - amd64
  
compiler:
  - gcc
  - clang

git:
  depth: 5

python:
  - "3.6"

matrix:
  allow_failures:
    - os: osx
  include:
    - compiler: clang
      env: SANITIZER="undefined" BUILD_TYPE=DEBUG CGNS=OFF FORTRAN=OFF
    - compiler: gcc
      arch: amd64
      env: MPI=ON H5VERSION=V18 USE_64BIT_INT=OFF
    - compiler: gcc
      arch: amd64
      env: MPI=ON H5VERSION=V110 USE_64BIT_INT=OFF
    - compiler: gcc
      arch: amd64
      env: MPI=ON H5VERSION=V18 USE_64BIT_INT=ON
    - compiler: clang
      env: MPI=ON THREADSAFE=ON H5VERSION=V18 FORTRAN=OFF
    - compiler: gcc
      env: KOKKOS=ON
    - compiler: gcc
      env: KOKKOS=ON MPI=ON H5VERSION=V18
    - compiler: gcc
      env: CGNS=OFF MPI=ON H5VERSION=V18
    - compiler: gcc
      env: FORTRAN=OFF
    - compiler: gcc
      env: ADIOS2=ON
    - compiler: gcc
      env: MPI=ON ADIOS2=ON
    - compiler: clang
      env: APPLICATIONS=OFF LEGACY=OFF FORTRAN=OFF

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - |
    if [ -n "$MPI" ]; then 
       sudo apt-get -y install -q mpich libmpich-dev
    else
       sudo apt-get -y install g++-7
       sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
       sudo apt-get -y install gfortran-7
       sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 90
    fi
  - sudo apt-get -y install cmake
  - sudo apt-get -y install libz-dev
  - sudo apt-get -y install python3
  - cmake --version
  - GNU_PARALLEL=OFF ./install-tpl.sh  >& install-tpl.out

before_script:

install:
  - cmake --version
  - ./cmake-config

script:
  - cd build
  - export LD_LIBRARY_PATH=/usr/local/lib
  - ctest -VV

env:
  global:
   - COMPILER=EXTERNAL

   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MrWZZDYlZlDQH7hP/3dZRdMns2Fo/MJRQ8yHLv7L3BEK+lO5m1vP3P4SDJ1vCs2DQOms3OAseqLg9/Wx6x7oytGmTMYq3qY865u8eiUC062523J8esi5oHzT7ofoPvYdomdE+rb6jaYyHsvAg2Tehm3f256QNheZFa9BKYenmfjQ4CUjcBWe22Fyhi9rmAdxxqhIiYfALEWk3c+pxcbO/k0Yk4uRaO0jZdHvPeX18s6t/NJFadbmziQkjt11EnQwofw1qJ+QhY+vfWruE3o1ZrYgHXm9c6g4GLHcaxpocX4XkfAilRWto07FKN2g8qqqQl6nLpKuAnjUa0lZnSNRSLVGtAlzb8mgCYEKqhcszmRKWGBKJM+vesvQBulLdLLWTvd6yCr7YEZgvQvQJ9EU6a+O07heanhK4GnMoGnpoyC4N6bycCCyJHXEmU9KC8oFzJq0V+q2SSCtSbdA8TpqKngXb/Kq42ntbYT+h7pX7K9dN/y2Vjo5F3UXNfV0bIkZ5v8kIqsRGtrRrg8vVbx1pm4VaMtLDZnRT5tWOgA9sIUntEg9hiiItYplfmsMdFz/WwDW0lota3L+9HNX8viIzyHtbZhnCzEKCeZ9f2V78ZW/IVLgwk+dtg78fCVweMNdyQwTdbENb1WFnyUgfv8hh4q5g+jWggdTTqubFQmTzAk="

addons:
  coverity_scan:
    project:
      name: "gsjaardema/seacas"
      description: "Build submitted via Travis CI"
    notification_email: gsjaardema@gmail.com

    build_command_prepend: 

    build_command: "THREADSAFE=ON ./cmake-config coverity"

    branch_pattern: coverity_scan
