version: 2.1

jobs:

  build_serial_gcc:
    machine:
      image: "ubuntu-2004:202010-01"
    environment:
      GNU_PARALLEL: OFF
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc-10 g++-10 gfortran-10'
      - run:
          name: Installing Third-Party Libraries
          command: './install-tpl.sh'
      - run:
          name: Configure
          command: 'mkdir build && cd build && ../cmake-config'
      - run:
          name: Build
          command: 'pwd && cmake --build build'
      - run:
          name: Test
          command: 'cd build && ctest -V'

  build_serial_clang:
    machine:
      image: "ubuntu-2004:202010-01"
    environment:
      GNU_PARALLEL: OFF
      COMPILER: clang
    steps:
      - checkout
      - run:
          name: Installing Clang
          command: 'sudo apt-get update && sudo apt-get install -y llvm clang gcc-9 g++-9 gfortran-9 && clang --version'
      - run:
          name: Installing Third-Party Libraries
          command: './install-tpl.sh'
      - run:
          name: Configure
          command: 'mkdir build && cd build && ../cmake-config'
      - run:
          name: Build
          command: 'pwd && cmake --build build'
      - run:
          name: Test
          command: 'cd build && ctest -V'

  build_parallel:
    machine:
      image: "ubuntu-2004:202010-01"
    environment:
      GNU_PARALLEL: OFF
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc-10 g++-10 gfortran-10'
      - run:
          name: Install MPI
          command: 'sudo apt-get -y install -q mpich libmpich-dev'
      - run:
          name: Installing Third-Party Libraries
          command: 'MPI=ON ./install-tpl.sh'
      - run:
          name: Configure
          command: 'mkdir build && cd build && ../cmake-config'
      - run:
          name: Build
          command: 'pwd && cmake --build build'
      - run:
          name: Test
          command: 'cd build && ctest -V'

workflows:
  version: 2
  build_all:
    jobs:
      - build_serial_gcc
      - build_parallel
