# This is a basic workflow to help you get started with Actions
name: SEACAS Spack build

# Controls when the action will run. Triggers the workflow on push
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack       # Where to clone Spack
        run: |
          spack external find
          spack compiler find

    - name: Build non-mpi SEACAS
        shell: bash -l {0}
        run: |
          spack spec seacas~mpi
          spack install seacas~mpi

    - name: Build parallel SEACAS
        shell: bash -l {0}
        run: |
          spack spec seacas
          spack install seacas

