name: CI Formatting
on:
  workflow_dispatch:

jobs:
  trailing:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Find Trailing Whitespace
        run: |
          set +e

          lines=$(git grep --cached -In '[[:blank:]]$' packages/seacas/applications packages/seacas/libraries)
          if [ ! -z "$lines" ]; then
             echo -e "\n The following lines contain trailing whitespace: \n"
             echo -e "${lines}"
             echo -e "\nFailed.\n"
             exit 1
          fi
          exit 0